---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
  - port: 4499
    targetPort: 4499
    nodePort: 30007
  type: NodePort
                   
